/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlinx.coroutines.*
import kotlin.system.*

fun main() {
    Activity1().main()
}

class Activity1() {
    fun main() {
        val time = measureTimeMillis {
            runBlocking {
                println("Weather forecast")
                printForecast()
                printTemperature()
            }
        }
        
        println("Execution time: ${time / 1000.0} seconds")
    }

    suspend fun printForecast() {
        delay(1000)
        println("Sunny")
    }

    suspend fun printTemperature() {
        delay(1000)
        println("30\u00b0C")
    }
}